name: 'Install dependencies for Catimini integration tests'
description: 'Installs required dependencies'
inputs:
  platform:
    description: 'Target platform'
    required: true
runs:
  using: "composite"
  steps:
    - if: startsWith(inputs.platform, 'ubuntu-')
      run : >-
        sudo apt install
        webkit2gtk-driver
        xvfb
      shell: bash
    - if: startsWith(inputs.platform, 'windows-')
      run: |
        cargo install --git https://github.com/chippers/msedgedriver-tool
        & "$HOME/.cargo/bin/msedgedriver-tool.exe"
        $PWD.Path >> $env:GITHUB_PATH
      shell: pwsh
