[package]
name = "catimini-ui"
version.workspace = true
description.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
build = "src-rust/build.rs"

[[bin]]
name = "catimini-run"
path = "src-rust/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }
image = "0.25.0"

[dependencies]
# Use feature recommended on https://github.com/tauri-apps/tauri/issues/13954#issuecomment-3155346630
tauri = { version = "2", default-features = false, features = ["wry", "compression", "x11", "test"] }
tauri-plugin-opener = "2"
catimini-lib = { path = "../catimini-lib" }
clap = { version = "4.5.42", features = ["derive"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(mobile)'] }
