name: Catimini Build
run-name: Building Catimini project
on: [push]
jobs:
  Catimini-Validation:
    # run on the matrix platform
    runs-on: ${{ matrix.platform }}
    strategy:
      # do not fail other matrix runs if one fails
      fail-fast: false
      # set all platforms our test should run on
      matrix:
        platform: [ubuntu-24.04, windows-latest]

    steps:
      - if: matrix.platform == 'ubuntu-24.04'
        name: "Install build dependencies (Linux)"
        run: >-
          sudo apt update &&
          sudo apt install
          libwebkit2gtk-4.1-dev
          build-essential
          curl
          wget
          file
          libxdo-dev
          libssl-dev
          libayatana-appindicator3-dev
          librsvg2-dev
          npm

      - if: matrix.platform == 'windows-latest'
        name: "Install rust toolchain (Windows)"
        uses: dtolnay/rust-toolchain@stable
      - if: matrix.platform == 'windows-latest'
        name: "Install NodeJs (Windows)"
        uses: actions/setup-node@v4

      - uses: actions/checkout@v4

      - working-directory: "catimini-ui"
        run: "npm install"
      - name: "Catimini Build"
        run: "npm --prefix catimini-ui run tauri build"
      - name: "Back-end unit tests"
        run: "cargo test"
      - name: "Front-end unit tests"
        run : "npm --prefix catimini-ui run test"

      - if: matrix.platform == 'ubuntu-24.04'
        name: "Install integration test dependencies (Linux)"
        run : >-
          sudo apt install
          webkit2gtk-driver
          xvfb
      - if: matrix.platform == 'windows-latest'
        name: "Install integration test dependencies (Windows)"
        run: |
          cargo install --git https://github.com/chippers/msedgedriver-tool
          & "$HOME/.cargo/bin/msedgedriver-tool.exe"
          $PWD.Path >> $env:GITHUB_PATH
      - working-directory: "integration_tests"
        run: "npm install"
      - name: "Run integration tests"
        run : "npm --prefix integration_tests test"
