name: Catimini Build
run-name: Building Catimini project
on: [push]
jobs:
  Catimini-Build-Linux:
    runs-on: ubuntu-24.04
    steps:
      - run: "sudo apt update"
      - run: >-
          sudo apt install
          libwebkit2gtk-4.1-dev
          build-essential
          curl
          wget
          file
          libxdo-dev
          libssl-dev
          libayatana-appindicator3-dev
          librsvg2-dev
          npm
          webkit2gtk-driver
          xvfb
      - uses: actions/checkout@v4
      - working-directory: "catimini-ui"
        run : "npm install"
      - run : "npm --prefix catimini-ui run tauri build"
      - run : "cargo test"
      - run : "npm --prefix catimini-ui run test"
      - run : >-
          sudo apt install
          webkit2gtk-driver
          xvfb
      - working-directory: "integration_tests"
        run: "npm install"
      - run : "npm --prefix integration_tests test"

  Catimini-Build-Windows:
    runs-on: windows-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/setup-node@v4
      - uses: actions/checkout@v4
      - working-directory: "catimini-ui"
        run : "npm install"
      - run : "npm --prefix catimini-ui run tauri build"
      - run : "cargo test"
      - run : "npm --prefix catimini-ui run test"
      - run: |
          cargo install --git https://github.com/chippers/msedgedriver-tool
          & "$HOME/.cargo/bin/msedgedriver-tool.exe"
          $PWD.Path >> $env:GITHUB_PATH
      - working-directory: "integration_tests"
        run: "npm install"
      - run : "npm --prefix integration_tests test"

