name: Catimini Build
run-name: Building Catimini project
on: [push]
jobs:
  Catimini-Validation:
    # run on the matrix platform
    runs-on: ${{ matrix.platform }}
    strategy:
      # do not fail other matrix runs if one fails
      fail-fast: false
      # set all platforms our test should run on
      matrix:
        build-type: ['Debug', 'Release']
        platform: [ubuntu-24.04, windows-2022]

    steps:
      - if: startsWith(matrix.platform, 'ubuntu-')
        name: "Install build dependencies (Linux)"
        run: >-
          sudo apt update &&
          sudo apt install
          libwebkit2gtk-4.1-dev
          build-essential
          curl
          wget
          file
          libxdo-dev
          libssl-dev
          libayatana-appindicator3-dev
          librsvg2-dev
          npm

      - if: startsWith(matrix.platform, 'windows-')
        name: "Install rust toolchain (Windows)"
        uses: dtolnay/rust-toolchain@stable
      - if: startsWith(matrix.platform, 'windows-')
        name: "Install NodeJs (Windows)"
        uses: actions/setup-node@v4

      - uses: actions/checkout@v4

      - working-directory: "catimini-ui"
        run: "npm install"
      - name: "Catimini Build"
        uses: ./.github/actions/tauri-build
        with:
          project-dir: 'catimini-ui'
          build-type: ${{ matrix.build-type }}
      - name: "Back-end unit tests"
        uses: ./.github/actions/cargo-cmd
        with:
          subcmd: 'test'
          build-type: ${{ matrix.build-type }}
      - name: "Front-end unit tests"
        run : "npm --prefix catimini-ui run test"

      - name: "Install integration test dependencies"
        uses: ./.github/actions/install-catimini-integration-tests-deps
        with:
          platform: ${{ matrix.platform }}
      - working-directory: "integration_tests"
        run: "npm install"
      - name: "Run integration tests"
        uses: ./.github/actions/run-catimini-integration-tests
        with:
          test-dir: 'integration_tests'
          build-type: ${{ matrix.build-type }}
